### ISSUE TITLE
normalize disagreement metric by default

### ISSUE THREAD

**Issue by dustinvtran** [google/uncertainty-metrics#29]
disagreement metric in codebase is vanilla disagreement.

we should fix that to normalized, at least in the average_pairwise meta function.

it's only normalized in the corruptions metrics of the baselines.

**Comment by dustinvtran** [comment]
Looking at the metric, it is in fact already normalized as an optional argument (user must pass in `errors`). So this may be more of an issue that baselines does not call the metric and pass in errors. @mhavasi

**Comment by JeremyNixon** [comment]
Closing, feel free to re-open if this is still at issue.
