### ISSUE TITLE
Take sqrt for l2

### ISSUE THREAD

**Issue by hendrycks** [google/uncertainty-metrics#46]
For the RMS (_root_ mean square) calibration error, I think
```
np.sum(np.square(weighted_calibration_error))
```
should be
```
np.sqrt(np.sum(np.square(weighted_calibration_error)))
```
Without the square root, the ECE often looks an order of magnitude larger than the RMS. Taking the root makes these on a more similar scale.
https://github.com/google/uncertainty-metrics/blob/master/uncertainty_metrics/numpy/general_calibration_error.py#L191

**Comment by dustinvtran** [comment]
Good catch! @JeremyNixon

**Comment by JeremyNixon** [comment]
Totally agree! We already take the square root at:
https://github.com/google/uncertainty-metrics/blob/master/uncertainty_metrics/numpy/general_calibration_error.py#L272

Definitely let me know if it is still in error.

**Comment by hendrycks** [comment]
I was calling get_calibration_error directly which keeps it squared. Maybe my way of using the functions is unusual though.

**Comment by JeremyNixon** [comment]
I see the value of that use case. The tricky condition is when the user wants a class conditional calibration metric - get_calibration_error is called one time per class, and those calibration errors are averaged. In this case, I believe that

np.sqrt(np.sum(calibration_error)) != 
np.sum(np.sqrt(calibration_error)).

Have a design for correctly implementing class conditional metrics and allowing for your use case simultaneously?

**Comment by hendrycks** [comment]
Squaring the result of get_calibration_error, summing, then taking the square root comes to mind, but I don't know if that's too inelegant.
